package models.utils;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.time.Duration;
import java.time.LocalDateTime;

public class CountDown implements Serializable {
    /*
     * This is the UID generated by the original submitted class. Keeping it
     * explicit allows old serialized greenhouse saves to remain readable.
     */
    private static final long serialVersionUID = 1655896597725709795L;

    private LocalDateTime targetTime;
    private int countingHours;

    public CountDown(int hours) {
        setCountingHours(hours);
    }

    public int getRemainingHours() {
        ensureTargetTime();

        Duration remaining =
            Duration.between(
                LocalDateTime.now(),
                targetTime
            );

        if (remaining.isZero() || remaining.isNegative()) {
            return 0;
        }

        long seconds = remaining.getSeconds();

        if (remaining.getNano() > 0) {
            seconds++;
        }

        long roundedHours =
            (seconds + 3599L) / 3600L;

        return (int) Math.min(
            Integer.MAX_VALUE,
            roundedHours
        );
    }

    public void setCountingHours(int hours) {
        countingHours = Math.max(0, hours);
        targetTime =
            LocalDateTime.now()
                .plusHours(countingHours);
    }

    public void finish() {
        countingHours = 0;
        targetTime = LocalDateTime.now();
    }

    private void ensureTargetTime() {
        if (targetTime == null) {
            targetTime =
                LocalDateTime.now()
                    .plusHours(
                        Math.max(0, countingHours)
                    );
        }
    }

    private void readObject(
        ObjectInputStream input
    ) throws IOException, ClassNotFoundException {
        input.defaultReadObject();
        ensureTargetTime();
    }
}
