package models;

import java.io.Serializable;
import java.util.ArrayList;

public class GreenHouse implements Serializable {
    /*
     * Generated by the original submitted class. Keeping it prevents changes
     * in this implementation from invalidating existing serialized users.
     */
    private static final long serialVersionUID = 8737255469961946666L;

    private static final int COLUMNS = 5;
    private static final int ROWS = 4;
    private static final int MAX_POTS = COLUMNS * ROWS;

    private User owner;
    private ArrayList<Pot> pots;

    public GreenHouse(User owner) {
        this.owner = owner;
        this.pots = new ArrayList<>();
        ensurePotLayout();
    }

    public String showAll() {
        ensurePotLayout();

        String ownerName =
            owner == null || owner.getName() == null
                ? "Unknown"
                : owner.getName();

        StringBuilder result =
            new StringBuilder(
                "--- GreenHouse Status for "
                    + ownerName
                    + " ---\n"
            );

        for (int row = 1; row <= ROWS; row++) {
            for (int column = 1; column <= COLUMNS; column++) {
                Pot pot =
                    getPotByPosition(
                        column,
                        row
                    );

                if (pot == null) {
                    result.append("[ Invalid ]\t");
                } else if (!pot.isUnlocked()) {
                    result.append("[ Locked ]\t");
                } else if (pot.getSeedling() == null) {
                    result.append("[ Empty  ]\t");
                } else if (pot.getRemainingHours() <= 0) {
                    result.append("[")
                        .append(pot.getSeedling())
                        .append(" (Ready)]\t");
                } else {
                    result.append("[")
                        .append(pot.getSeedling())
                        .append(" (")
                        .append(pot.getRemainingHours())
                        .append("h)]\t");
                }
            }

            result.append("\n");
        }

        return result.toString().trim();
    }

    public String growNow(int x, int y) {
        Pot pot = getPotByPosition(x, y);

        return pot == null
            ? "Error: Invalid coordinates."
            : pot.growNow();
    }

    public String plantPot(int x, int y) {
        Pot pot = getPotByPosition(x, y);

        return pot == null
            ? "Error: Invalid coordinates."
            : pot.plant();
    }

    public String collectPot(int x, int y) {
        Pot pot = getPotByPosition(x, y);

        return pot == null
            ? "Error: Invalid coordinates."
            : pot.collect();
    }

    public Pot getPotByPosition(int x, int y) {
        if (x < 1
            || x > COLUMNS
            || y < 1
            || y > ROWS) {
            return null;
        }

        ensurePotLayout();

        int index =
            (y - 1) * COLUMNS
                + (x - 1);

        return pots.get(index);
    }

    public void attachOwner(User newOwner) {
        owner = newOwner;
        ensurePotLayout();
    }

    private void ensurePotLayout() {
        ArrayList<Pot> existing =
            pots == null
                ? new ArrayList<>()
                : pots;

        ArrayList<Pot> normalized =
            new ArrayList<>(MAX_POTS);

        for (int y = 1; y <= ROWS; y++) {
            for (int x = 1; x <= COLUMNS; x++) {
                Pot matching = findPot(existing, x, y);

                if (matching == null) {
                    matching = new Pot(owner, x, y);
                } else {
                    matching.attachOwner(owner);
                }

                normalized.add(matching);
            }
        }

        pots = normalized;
    }

    private Pot findPot(
        ArrayList<Pot> source,
        int x,
        int y
    ) {
        for (Pot pot : source) {
            if (pot != null
                && pot.getX() == x
                && pot.getY() == y) {
                return pot;
            }
        }

        return null;
    }
}
