package models;

import models.factory.builder.PlantType;
import models.utils.CountDown;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class Pot implements Serializable {
    /*
     * Generated by the original submitted class. Do not change: old User saves
     * contain serialized Pot instances.
     */
    private static final long serialVersionUID = -8664331775119579323L;

    private static final int MARIGOLD_GROW_HOURS = 2;
    private static final int RANDOM_PLANT_GROW_HOURS = 8;
    private static final int MARIGOLD_REWARD = 500;

    private boolean unlocked;
    private PlantType seedling;
    private int x;
    private int y;
    private CountDown timer;
    private User user;

    public Pot(User user, int x, int y) {
        this.x = x;
        this.y = y;
        this.user = user;
        this.seedling = null;
        this.unlocked = y == 1;
    }

    public String plant() {
        if (!unlocked) {
            return "Error: This pot is locked!";
        }

        if (seedling != null) {
            return "Error: Pot already has a plant.";
        }

        if (user == null) {
            return "Error: Pot owner is unavailable.";
        }

        List<PlantType> candidates =
            getUnlockedPlantCandidates();

        boolean plantMarigold =
            candidates.isEmpty()
                || ThreadLocalRandom.current()
                .nextBoolean();

        if (plantMarigold) {
            seedling = PlantType.MARIGOLD;
            timer = new CountDown(
                MARIGOLD_GROW_HOURS
            );
        } else {
            seedling =
                candidates.get(
                    ThreadLocalRandom.current()
                        .nextInt(candidates.size())
                );

            timer = new CountDown(
                RANDOM_PLANT_GROW_HOURS
            );
        }

        return "Planted "
            + seedling.name()
            + " at ("
            + x
            + ", "
            + y
            + ").";
    }

    public String collect() {
        if (!unlocked) {
            return "Error: This pot is locked!";
        }

        if (seedling == null) {
            return "Error: There is no plant here to collect!";
        }

        if (user == null) {
            return "Error: Pot owner is unavailable.";
        }

        int remainingHours = getRemainingHours();

        if (remainingHours > 0) {
            return "Error: The plant is not fully grown yet. Remaining: "
                + remainingHours
                + " hours.";
        }

        String result;

        if (seedling == PlantType.MARIGOLD) {
            user.addCoins(MARIGOLD_REWARD);
            result =
                "Collected a Marigold! Earned 500 coins.";
        } else {
            user.addToBoostList(seedling);
            result =
                "Collected "
                    + seedling.name()
                    + "! Boost saved.";
        }

        seedling = null;
        timer = null;

        return result;
    }

    public String growNow() {
        if (!unlocked) {
            return "Error: This pot is locked!";
        }

        if (seedling == null) {
            return "Error: Pot is empty.";
        }

        if (user == null) {
            return "Error: Pot owner is unavailable.";
        }

        int remainingHours = getRemainingHours();

        if (remainingHours <= 0) {
            return "Error: Plant is already fully grown!";
        }

        if (user.getDiamonds() < remainingHours) {
            return "Error: Not enough diamonds. You need "
                + remainingHours
                + " diamonds.";
        }

        user.addDiamonds(-remainingHours);

        if (timer != null) {
            timer.finish();
        }

        return "Used "
            + remainingHours
            + " diamonds to force grow. The plant is ready!";
    }

    public void unlock(boolean open) {
        unlocked = open;
    }

    public void attachOwner(User owner) {
        user = owner;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    public String getSeedling() {
        return seedling == null
            ? null
            : seedling.toString();
    }

    public PlantType getSeedlingType() {
        return seedling;
    }

    public int getRemainingHours() {
        if (seedling == null || timer == null) {
            return 0;
        }

        return timer.getRemainingHours();
    }

    public boolean isUnlocked() {
        return unlocked;
    }

    private List<PlantType>
    getUnlockedPlantCandidates() {
        ArrayList<PlantType> result =
            new ArrayList<>();

        for (PlantType type : user.getUnlockedPlants()) {
            if (type != null
                && type != PlantType.MARIGOLD
                && !result.contains(type)) {
                result.add(type);
            }
        }

        return result;
    }
}
